# Generated by Django 5.2.6 on 2025-09-10 20:03

from django.contrib.auth import models as auth_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                # Use default Django UserManager since custom manager was removed
                ('objects', auth_models.UserManager()),
            ],
        ),
    ]
