# Generated by Django 5.2.6 on 2025-09-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abtests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abtests.abtestvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='uservariant',
            unique_together={('user', 'ab_test')},
        ),
    ]
