# Generated by Django 5.2.6 on 2025-09-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Номер телефона для каналов типа 'call'", max_length=20, null=True),
        ),
    ]
