# Generated by Django 5.2.6 on 2025-09-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Call'), ('callback', 'Callback'), ('messenger', 'Messenger'), ('chat', 'Chat'), ('form', 'Form')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('online_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('show_in_top', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='projects.project')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
